export const teamList = [
  {
    id: 1,
    name: "Arnav Sangekar",
    image: "/images/profile.png",
    position: "Chairperson",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 2,
    name: "Amey Pandit",
    image: "/images/profile.png",
    position: "Secretary",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 3,
    name: "Riya Shetty",
    image: "/images/profile.png",
    position: "Deputy Secretary",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 4,
    name: "Ritik Yadav",
    image: "/images/profile.png",
    position: "Deputy Secretary",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 5,
    name: "Khushi Kashyap",
    image: "/images/profile.png",
    position: "Event Head",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 6,
    name: "Gautam Mishra",
    image: "/images/profile.png",
    position: "Registration Head ",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 7,
    name: "Keshav Jha",
    image: "/images/profile.png",
    position: "Publicity Head",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 8,
    name: "Vedant Farkade",
    image: "/images/profile.png",
    position: "Technical Head",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 9,
    name: "Jay Patel",
    image: "/images/profile.png",
    position: "Assistant Technical Head",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 10,
    name: "Akash Kolakkal",
    image: "/images/profile.png",
    position: "Web Designer",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 11,
    name: "Kaushik Dhara",
    image: "/images/profile.png",
    position: "Treasurer",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 12,
    name: "Sakshi Adhikar",
    image: "/images/profile.png",
    position: "Documentation Head",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 13,
    name: "Sarita Mukkani",
    image: "/images/profile.png",
    position: "Documentation Head",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
];
export const eventList = [
  {
    id: 1,
    image: "/images/hackathon.jpg",
    title: "Hackmania",
    dated: "Oct 2023",
    description: "A great hackathon for starters!",
  },
  {
    id: 2,
    image: "/images/hackathon.jpg",
    title: "Hackmania",
    dated: "Oct 2023",
    description: "A great hackathon for starters!",
  },
  {
    id: 3,
    image: "/images/hackathon.jpg",
    title: "Hackmania",
    dated: "Oct 2023",
    description: "A great hackathon for starters!",
  },
];
