export const teamList = [
  {
    id: 1,
    name: "Jamil Shaikh",
    image: "/images/profile.png",
    position: "Head",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 2,
    name: "Jamil Shaikh",
    image: "/images/profile.png",
    position: "Head",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 3,
    name: "Jamil Shaikh",
    image: "/images/profile.png",
    position: "Head",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 4,
    name: "Jamil Shaikh",
    image: "/images/profile.png",
    position: "Head",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
  {
    id: 5,
    name: "Jamil Shaikh",
    image: "/images/profile.png",
    position: "Head",
    slogan: "Here's my gift to CSI",
    linkedIn: "link:linkedin",
    github: "link:github",
  },
];
export const eventList = [
  {
    id: 1,
    image: "/images/hackathon.jpg",
    title: "Hackmania",
    dated: "Oct 2023",
    description: "A great hackathon for starters!",
  },
  {
    id: 2,
    image: "/images/hackathon.jpg",
    title: "Hackmania",
    dated: "Oct 2023",
    description: "A great hackathon for starters!",
  },
  {
    id: 3,
    image: "/images/hackathon.jpg",
    title: "Hackmania",
    dated: "Oct 2023",
    description: "A great hackathon for starters!",
  },
];
